spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mantenweb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
